import { Link } from 'react-router-dom'
import RailRouteMap from '../components/RailRouteMap'
import ExperiencePhotoCredit from '../components/ExperiencePhotoCredit'
import './Experience2027.css'

const stays = [
  { city: 'Vienna', dates: 'May 20–23', image: 'vienna', line: 'Imperial history, art, and a day in Bratislava.', country: 'Austria' },
  { city: 'Prague', dates: 'May 24–25', image: 'prague', line: 'Old Town streets and the Vltava.', country: 'Czech Republic' },
  { city: 'Berlin', dates: 'May 26–29', image: 'berlin', line: 'History, government, and a day in Dresden.', country: 'Germany' },
  { city: 'Hamburg', dates: 'May 30–31', image: 'hamburg', line: 'A port city and a day by the Baltic Sea.', country: 'Germany' }
]

export default function LookingAheadPage() {
  return <main id="main" tabIndex="-1" className="eee-page">
    <section className="eee-hero"><div className="shell eee-hero-inner"><div className="eee-hero-copy"><p className="eyebrow">St. Bonaventure University Business School · May 2027</p><h1>The European<br /><em>Economic Experience</em></h1><p className="eee-tagline">Same world. Bigger perspective.</p><p>Four city stays, three day trips, and a course that brings Europe into your education.</p><div className="eee-actions"><Link className="eee-button" to="/2027/presentation">Explore the web presentation <span aria-hidden="true">↗</span></Link><a className="eee-text-link" href="#route">Explore the route ↓</a></div></div><div className="eee-hero-image"><img src="/eee-2027/hero.webp" alt="Illustrated European cityscape at sunset from the European Economic Experience presentation" /><span>Artwork from the EEE information-session presentation</span></div></div></section>
    <section className="eee-facts"><div className="shell eee-facts-inner"><div><strong>14</strong><span>days · May 19–June 1</span></div><div><strong>4</strong><span>countries · Austria, Slovakia, Czech Republic, Germany</span></div><div><strong>3</strong><span>credits · proposed ECO 499-EE course</span></div></div></section>
    <section className="shell eee-section" id="journey"><div className="eee-heading"><p className="eyebrow">Your possible journey</p><h2>See more than one side of Europe.</h2><p>Four proposed city stays, with day trips along the way. Depart Buffalo May 19 and return June 1, according to the information-session slides.</p></div><div className="eee-stay-grid">{stays.map((stay,index)=><article key={stay.city} className="eee-stay"><a className="eee-stay-main" href="#route" onClick={() => window.dispatchEvent(new CustomEvent('sbu-select-city', { detail: stay.city.toLowerCase() }))}><div className="eee-stay-image"><img src={`/eee-2027/${stay.image}.webp`} alt={`${stay.city} view`} loading="lazy" /></div><div className="eee-stay-copy"><span>0{index+1} / {stay.dates} · {stay.country}</span><h3>{stay.city}</h3><p>{stay.line}</p><b>Explore on the map ↗</b></div></a><ExperiencePhotoCredit image={stay.image} /></article>)}</div></section>
    <RailRouteMap />
    <section className="eee-day-section"><div className="shell eee-day-layout"><div><p className="eyebrow">How a day could work</p><h2>Together in the morning. Your own route afterward.</h2><p>On selected mornings, the group meets for required activities. Later, students can explore eligible stops with a buddy or group, record their discoveries, and return by the required check-in time. The specific activities and point requirements are still being planned.</p><Link className="eee-button" to="/2027/presentation#explore">See an example afternoon <span aria-hidden="true">↗</span></Link></div><div className="eee-example"><p className="eyebrow">Example · Vienna</p><h3>One neighborhood.<br />Four points.</h3><div className="eee-example-images"><img src="/eee-2027/belvedere.webp" alt="Upper Belvedere and its gardens" loading="lazy" /><img src="/eee-2027/schonbrunn.webp" alt="Schönbrunn Palace grounds photographed on the 2025 trip" loading="lazy" /></div><div className="eee-example-credits"><ExperiencePhotoCredit image="belvedere" /><ExperiencePhotoCredit image="schonbrunn" /></div><p>Upper Belvedere <strong>3 points</strong> + Belvedere Gardens <strong>1 point</strong>. The presentation suggests roughly 2–3½ hours at the stops, plus transit and breaks.</p></div></div></section>
    <section className="shell eee-section eee-details" id="details"><div><p className="eyebrow">The practical details</p><h2>Start planning.<br />Stay flexible.</h2><p>The information-session slides offer a working plan. Confirmed itinerary, course, application, and payment details will follow.</p><a className="eee-text-link" href="/downloads/european-economic-experience-2027.pptx" download>Download the original PowerPoint ↧</a></div><div><dl><div><dt>Proposed dates</dt><dd>May 19–June 1, 2027</dd></div><div><dt>Course</dt><dd>Spring 2027 · ECO 499-EE · 3 credits, as proposed in the slides</dd></div><div><dt>Estimated cost</dt><dd>Approximately $4,175 per traveler; planning range $3,966–$4,384. Two travelers per room; planning exchange rate €1 = US$1.20. These are estimates, not a final price.</dd></div><div><dt>Questions?</dt><dd><a href="mailto:mwilson@sbu.edu">Dr. Mark Wilson</a> · <a href="mailto:bposmani@sbu.edu">Dr. Ben Posmanick</a></dd></div></dl><details className="eee-cost-breakdown"><summary>See the slide’s estimated cost breakdown</summary><table><caption>Planning estimates per traveler, from the EEE information-session slides</caption><tbody><tr><th scope="row">Airfare</th><td>$1,400</td></tr><tr><th scope="row">Hotels · 12 nights</th><td>$1,005</td></tr><tr><th scope="row">City passes + local transit</th><td>$600</td></tr><tr><th scope="row">Rail · 7 journeys</th><td>$321.60</td></tr><tr><th scope="row">Additional fees</th><td>$600</td></tr><tr><th scope="row">Contingency</th><td>$250</td></tr><tr className="eee-cost-total"><th scope="row">Slide total</th><td>$4,176.60</td></tr></tbody></table></details></div></section>
    <section className="eee-end"><div className="shell"><p className="eyebrow">European Economic Experience · 2027</p><h2>Same challenges.<br />A bigger world.</h2><div className="eee-actions"><Link className="eee-button" to="/2027/presentation">Open the web presentation <span aria-hidden="true">↗</span></Link><Link className="eee-text-link" to="/2025">See the 2025 trip →</Link></div></div></section>
  </main>
}
